### PR TITLE
add TS_FEED tile style to show message feed

### LINKED ISSUE #25: Ability to display plain text or HTML on a screen
In addition to being able to display tiles / keypads etc., would be useful to be able to display plain text or even HTML on a screen.

Useful for serving latest news / weather...

### PR DESCRIPTION
**Pull request by moinmoin-sh**
EDIT:  feeds are tile dependent 

standard :
  chevron-right  `>`  chosen as top-right indicator for tile type `feed `
  new posts are pushed to front (shown as top post on feed)
  holds up to 5 posts, if > 5 -> oldest post removed

 
elements :
`id` : optional, can be any number, needed if id-related deletion is wanted
`head `: optional head of post  
`body `: optional body of post
at least one of `body `|| `head `is required, otherwise ignored

proposed payloads :  ( I assume you have better ideas for the payloads )

add post to the top of the list
```
{
"tiles":
  [
    {
    "screen":"1",
    "tile":"3",
    "messageFeed":
	   {
	   "addPost":{"id":1, "head":"Head 1", "body":"Body 1"}
	   }
    }
  ]
}


```
remove post by id, id == 0 || missing -> remove all
```
{
"tiles":
  [
    {
    "screen":"1",
    "tile":"3",
    "messageFeed":
	   {
	   "removePost":{"id":1}
	   }
    }
  ]
}

```

closes #25

### CODE REVIEW

**Review by sumnerboy12 — APPROVED** [review]
Looks good Moin - so the idea is you maintain a feed independent of any tiles, and then can view that feed by configuring one or more tiles as `"style":"feed"`? They will all link to the one feed.

Is there a reason we can't have different feeds for different tiles?

**Comment by moinmoin-sh** [comment]
I didn't expect that multi feeds would be required. Looking at crippled feeds on the TP32 doesn't seem to be desirable nowadays where evrybody carries a smartphone all day. So I tried to implement a fairly simple resource saving solution.
Do you have something special in mind?

**Comment by sumnerboy12** [comment]
I just know that once you add this feature, people will find ways to use it. Could be a 5 day weather forecast with a tile for each day, and clicking thru shows the detailed forecast. Could be a set of tiles for a group of computers, and clicking thru shows monitoring/status details for each. Could be calendar feeds for each member of the family.

I am sure others will think of better use-cases.

**Comment by moinmoin-sh** [comment]
Good point. I've underestimated the creativty of users which we want to challenge. I would have solved your examples with sub screens but a feed may be a good solution as well, unfortunately with limited formatting features.
I'll check for a tile based implementation.

**Comment by moinmoin-sh** [comment]
feeds are tile dependent now.

I can't decide for an icon ...

**Pull request merged**
