### PR TITLE
Rotation for bg image

### PR DESCRIPTION
**Pull request by moinmoin-sh**
This allows to rotate the bg image.

EDIT: updated to match latest changes 

An additional parameter is added to the payload and the stucture of the payload has changed (sorry):

```
{
  "tiles":[
    {
      "screen": <number>,
      "tile": <number>,
      "bgImage": 
      {
        "base64": "<encodeBase64(.png)>",
        "zoom": <number>,
        "angle": <number>
        "offset": [<x number>,<y number>],
      }
    }
  ]
}
```

- ` "angle":<number>` is an integer that defines the rotation angle in increments of 0.1 deg (eg 900 = 90 deg)
- `+ <number>` rotates CW , `- <number>` rotates CCW 
- each rotation is absolute from origin (not incremental)

- key is now `"bgImage"`
- `"bgImage":{}`  removes the bg image
- `"bgImage":{ without "base64"}` applies the properties (zoom, angle, offset) to the previously loaded image -> changing the properties of an existing image doesn't require to load the image again.
- If the image is removed once, it has to be reloaded. 
- Missing properties are set to default. With all properties missing the original image is positioned in the center of the tile.

### CODE REVIEW

**Comment by sumnerboy12** [comment]
I wonder if we should look to re-organise this payload a bit - the `zoom`, `posOffset` and `angle` are image only related but they are in the root tile payload. 

What about something like;

```json
{
  "tiles":[
    {
      "screen": <number>,
      "tile": <number>,
      "image": {
        "base64": "<encodeBase64(.png)>",
        "zoom": <number>,
        "offset": [<x number>,<y number>],
        "angle": <number>
      }
    }
  ]
}
```

**Comment by moinmoin-sh** [comment]
That makes sense. I was already thinking about an additional cmnd/ that set the parameters of a previously sent image which saves sending and rendering the same image everytime 

```
{
  "tiles":[
    {
      "screen": <number>,
      "tile": <number>,
      "imageProperties": {
        "zoom": <number>,
        "offset": [<x number>,<y number>],
        "angle": <number>
      }
    }
  ]
}
```

**Comment by sumnerboy12** [comment]
Would it make sense to keep everything in the one `"image": {}` payload, and if you don't want/need to send the image itself you just leave out the `"base64": <>` field (i.e. if already sent earlier)?

**Comment by moinmoin-sh** [comment]
OK, so empty "image"  (may be change to "bgImage") payload means `remove the image` 
missing/empty "base64" means `use existing image`

**Comment by sumnerboy12** [comment]
That sounds good to me.

**Comment by moinmoin-sh** [comment]
Please see updated top comment.

**Comment by sumnerboy12** [comment]
Looks great, ship it!

**Pull request merged**
